### ISSUE TITLE
Question: how side-chain block header comes to consensus.

### ISSUE THREAD

**Issue by ToWorld** [ontio/cross-chain#16]
I have studied the framework of Cross-Chain based on ontology, and I have two questions, as follows:
Q1:How side-chain block header come to consensus?
Q2:How to make sure the validators in current term stored on Main-Chain is consistent with the side-chain?

**Comment by tanZiWen** [comment]
Q1: sorry, what's the meaning about it, side-chain has its own consensus mechanism, side-chain may have two way consensus mechanism, the block is confirm in current term, we call it finality like Ontology, we use VBFT consensus algorithms; the other way is like Bitcoin, the block can't be confirmed in current term, our cross-chain protocol can support two of them, it is a heterogeneous chain protocol.
Q2: the header of side-chain need contain the sigs of validators when Relayer transfer it to Main-Chain. the header sync is an independent module on Main-Chain, when Relayer transfer side-chain 's header to Main-chain, the Main-Chain will verify the validators's sigs, if it is legal, it will be stored on Main-chain.

**Comment by ToWorld** [comment]
Thank you for your response.
Let's continue to talk about the second question.

Q1: You mean that at least 2/3 sig in each block based on ontology with VBFT or only key blocks have at least 2/3 sig?

Q2: Furthermore, which node the relayer chooses to get block header, I mean that if it is possible the specific node in side chain provides a fake and malicious block header and how to recognize it?

Q3: How to validate if the new validators corresponding to next term are right but making a fake validators set?

**Comment by tanZiWen** [comment]
Q1: yes, each block at least 2/3 sigs can reach a consensus.
Q2: every one can become the relayer, it is not important, because it can't impact safe of cross chain. About the side chain fake, this is a good question, every side chain who want to join in the cross chain group, it need to deposit some tokens, if side chain do evil, it will to be punished. About how to recognize it, it is difficult on chain. we design some governance mechanism, it decide by all validators, it need 2/3 sigs of all validators. [side chain malicious action ](https://github.com/ontio/documentation/blob/master/multichain/Ontology%20Multichain%20Design.pdf), you can review the section 6.
Q3: About switch consensus nodes, the last of block in previous term contain information of  validators in next term.

**Comment by ToWorld** [comment]
Thank you and I basically understand the core concept of ontology cross-chain.
However, I have the last question, as follows:
Firstly，for the bft consensus, you can get 2/3 sig in each block so that you can recognize if the validators are correct but fake, with it you can validate if a block is valid.
Then, for the pow consensus, specially for BitCoin, the cost of making a fake block is much so that you have to give up making a fake block.
However, for the dpos consensus, such as EOS，you can't get 2/3 sig in each block, even you can't get validators in each block header, how the Main-Chain makes sure that the block header and validators set received from relayers are valid?

**Comment by tanZiWen** [comment]
About the pow consensus, it has fake block is normal, Relayer sync header of side-chain to Main-chain may sync a fake header to Main-chain, so the point is how can we know which header is right, the module of sync header of side-chain on main-chain need to have a rule to distinguish it, we implement a module same with SPV client to choice the longest chain.
About EOS consensus, it is asynchronous bft, so it has finality, but it isn't finality in current block, it need after 15 blocks. Now EOS has 21 consensus nodes, according to bft, it need at least 2/3 sigs, so after 15 blocks the header is valid.
About cross-chain sync header, we just distinguish them into two categories, one of them hasn't Byzantine, it can't finality in blocks, it may be safe after 6 blocks, we need to implement them same with SPV client, other of them has Byzantine, whether it's asynchronous Byzantine like EOS, or it has Byzantine in current block like Ontology, we through 2/3 sigs to validate the block header.

**Comment by ToWorld** [comment]
I have no doubt that how many blocks to wait for different consensus algorithms.
However, for EOS, I think that nobody can get actual 2/3 validators or sig in any block but an irreversible block flag, So how to validate the validation of EOS block (it means that how to get current term validators and how to prove the validators are correct because you can't get validators set in any block) based on ontology cross-chain framework

**Comment by tanZiWen** [comment]
About dPos irreversible block, you can review this article https://steemit.com/dpos/@dantheman/dpos-consensus-algorithm-this-missing-white-paper
i think it can solve your question.
